### ISSUE TITLE
PushButton loses PressEnded when clicking the button very fast

### ISSUE THREAD

**Issue by HakanL** [WildernessLabs/Meadow.Foundation#344] opened 2022-06-06 22:09 UTC
I have an application that subscribes to both PressStarted and PressEnded. I log to the console in the first line of each method. If I click the button super-fast then I only receive the PressStarted event, PressEnded is never invoked. Pressing the button normally works fine.

**Comment by HakanL** [comment] 2022-06-06 22:12
It looks like the issue is in this piece of code, I assume the elapsed time is 0 (immeasurable):
https://github.com/WildernessLabs/Meadow.Foundation/blob/e532eef01b71206038a0e8c4edfb6bf7afc7ef36/Source/Meadow.Foundation.Core/Sensors/Buttons/PushButton.cs#L195

**Comment by adrianstevens** [comment] 2022-07-12 00:43
Thanks @HakanL - I've tested and it looks like we're losing the event. I think we can remove that check regardless (I don't believe it buys us anything) but I don't think this will be fixed until we have JIT support (i.e. I think we're losing the event due to performance)

**Comment by HakanL** [comment] 2022-07-12 07:29
Thanks @adrianstevens, I'm not sure if we're losing the event due to performance, I switched to use a direct digital input and I don't get any lost events.

**Comment by adrianstevens** [comment] 2022-11-17 19:45
We should retest with JIT enabled on RC1

**Comment by adrianstevens** [comment] 2023-01-25 20:09
I haven't been able to reproduce this behavior on new versions of the OS - closing issue but don't hesitate to reopen

**Closed by adrianstevens** 2023-01-25 20:09 UTC
Labels: Bug - Pri 2
